// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaeafpHvTIcllfg0ltMceGSTaJKSPbnCA',
    appId: '1:345483805700:android:1d82f645e90eeda80fe151',
    messagingSenderId: '345483805700',
    projectId: 'chat-app-4bb6b',
    storageBucket: 'chat-app-4bb6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZbNSbzHNQcGCHePunUv6QnGfbNLpSY2Y',
    appId: '1:345483805700:ios:931071f2b8120f110fe151',
    messagingSenderId: '345483805700',
    projectId: 'chat-app-4bb6b',
    storageBucket: 'chat-app-4bb6b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZbNSbzHNQcGCHePunUv6QnGfbNLpSY2Y',
    appId: '1:345483805700:ios:931071f2b8120f110fe151',
    messagingSenderId: '345483805700',
    projectId: 'chat-app-4bb6b',
    storageBucket: 'chat-app-4bb6b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeOyaSPLElPrqhnIJHAp1Fn6s7klj8bbE',
    appId: '1:345483805700:web:7c068e1f39aa24a40fe151',
    messagingSenderId: '345483805700',
    projectId: 'chat-app-4bb6b',
    authDomain: 'chat-app-4bb6b.firebaseapp.com',
    storageBucket: 'chat-app-4bb6b.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeOyaSPLElPrqhnIJHAp1Fn6s7klj8bbE',
    appId: '1:345483805700:web:7c068e1f39aa24a40fe151',
    messagingSenderId: '345483805700',
    projectId: 'chat-app-4bb6b',
    authDomain: 'chat-app-4bb6b.firebaseapp.com',
    storageBucket: 'chat-app-4bb6b.firebasestorage.app',
  );

}